totals_by_city='1UQFjCQDb-h9KVJTNlIhKluciEkucyNvZcLTylKoytj4'


hospitalized_quarantined_by_date = '1SJzZixY1PUdC9mcLCBfP9aACJ996vGGzLTw8oNTJl4w'
new_cases_new_tested_by_week = '1H-KdCx5VwEq26-rphnlYTyROJagpdJ5OfHjcfqU1QKs'
rolling_totals ='1ATpPcm8FWUsLkhPq-T28g_wN3uH_806pds4faAbojcQ'
totals_per_day = '1z_J5cd-6gUXfmeHfYz4UTnJy93M7___0xlsgZPfqMvY'
totals_by_age = '1dCXPQK7if-ExIZYuOQXX1KBscdm_WX2LOuvH0nQy_VE'
totals_by_gender = '1mxNutNw5GB3lSMM2gmHXZoquzebyEmwdBSnEmnwDSNE'